Repository online-ml/river, pull requests merged in 2021-01, with the labels that each got.

#397 Bandits regressors for model selection (new PR to use Github CI/CD)
  river/expert/__init__.py
  river/expert/bandit.py
  river/utils/math.py
Labels: Type: Feature

#451 Enforce SRP reproducibility for different Numpy versions
  river/ensemble/streaming_random_patches.py
Labels: Type: Bug

#457 Use the log-sum-exp trick in the NB leaf models
  river/tree/_tree_utils.py
Labels: Type: Improvement
