Repository online-ml/river, pull requests merged in 2021-03, with the labels that each got.

#469 Implementation of Denstream for clustering
  river/cluster/__init__.py
  river/cluster/denstream.py
Labels: Type: Feature

#502 Sentence classification - Doc - Example
  docs/examples/sentence_classification.ipynb
  docs/examples/sentence_classification.md
  docs/examples/sentence_classification_files/sentence_classification_14_0.svg
  docs/examples/sentence_classification_files/sentence_classification_19_0.svg
  docs/examples/sentence_classification_files/sentence_classification_31_0.svg
Labels: Type: Documentation

#488 Make tree splitters public
  docs/examples/sentence_classification.md
  docs/user-guide/.pages
  docs/user-guide/on-hoeffding-trees.ipynb
  river/ensemble/adaptive_random_forest.py
  river/evaluate/__init__.py
  river/evaluate/tracks.py
  river/stats/test_mean_var_cov.py
  river/tree/__init__.py
  river/tree/_attribute_observer/__init__.py
  river/tree/_attribute_observer/numeric_attribute_regression_quantizer_observer.py
  river/tree/_attribute_test/__init__.py
  river/tree/_attribute_test/nominal_binary_test.py
  river/tree/_attribute_test/nominal_multiway_test.py
  river/tree/_attribute_test/numeric_binary_test.py
  river/tree/_attribute_test/numeric_multiway_test.py
  river/tree/_attribute_test/split_suggestion.py
  river/tree/_nodes/arf_htc_nodes.py
  river/tree/_nodes/arf_htr_nodes.py
  river/tree/_nodes/base.py
  river/tree/_nodes/efdtc_nodes.py
  river/tree/_nodes/hatc_nodes.py
  river/tree/_nodes/hatr_nodes.py
  river/tree/_nodes/htc_nodes.py
  river/tree/_nodes/htr_nodes.py
  river/tree/_nodes/isouptr_nodes.py
  river/tree/_tree_utils.py
  river/tree/extremely_fast_decision_tree.py
  river/tree/hoeffding_adaptive_tree_classifier.py
  river/tree/hoeffding_adaptive_tree_regressor.py
  river/tree/hoeffding_tree.py
  river/tree/hoeffding_tree_classifier.py
  river/tree/hoeffding_tree_regressor.py
  river/tree/isoup_tree_regressor.py
  river/tree/label_combination_hoeffding_tree.py
  river/tree/setup.py
  river/tree/splitter/__init__.py
  river/tree/splitter/base_splitter.py
  river/tree/splitter/ebst_splitter.py
  river/tree/splitter/exhaustive_splitter.py
  river/tree/splitter/gaussian_splitter.py
  river/tree/splitter/histogram_splitter.py
  river/tree/splitter/nominal_splitter_classif.py
  river/tree/splitter/nominal_splitter_reg.py
  river/tree/splitter/qo_splitter.py
  river/tree/splitter/tebst_splitter.py
  river/tree/test_splitter.py
Labels: Type: Improvement
