Repository online-ml/river, pull requests merged in 2022-06, with the labels that each got.

#957 Move root `__init__` imports to a new `api` module
  docs/recipes/on-hoeffding-trees.ipynb
  docs/releases/unreleased.md
  river/__init__.py
  river/api.py
  river/compose/__init__.py
  river/compose/pipeline.py
  river/compose/test_.py
  river/datasets/__init__.py
  river/datasets/synth/agrawal.py
  river/datasets/synth/anomaly_sine.py
  river/datasets/synth/concept_drift_stream.py
  river/datasets/synth/friedman.py
  river/datasets/synth/hyper_plane.py
  river/datasets/synth/led.py
  river/datasets/synth/logical.py
  river/datasets/synth/mixed.py
  river/datasets/synth/mv.py
  river/datasets/synth/planes_2d.py
  river/datasets/synth/random_rbf.py
  river/datasets/synth/random_tree.py
  river/datasets/synth/sea.py
  river/datasets/synth/sine.py
  river/datasets/synth/stagger.py
  river/datasets/synth/waveform.py
  river/ensemble/adaptive_random_forest.py
  river/ensemble/streaming_random_patches.py
  river/metrics/cross_entropy.py
  river/multioutput/chain.py
  river/optim/base.py
  river/optim/losses.py
  river/rules/amrules.py
  river/test_estimators.py
  river/tree/extremely_fast_decision_tree.py
  river/tree/hoeffding_adaptive_tree_classifier.py
  river/tree/hoeffding_tree_classifier.py
  river/tree/splitter/ebst_splitter.py
  river/tree/splitter/qo_splitter.py
  river/tree/test_splitter.py
  river/tree/test_trees.py
  river/utils/__init__.py
  river/utils/context_managers.py
  river/utils/inspect.py
Labels: Feature

#960 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#959 Update logo.svg
  README.md
  docs/benchmarks/index.md
  docs/img/favicon.ico
  docs/img/icon.png
  docs/img/logo.svg
  docs/img/logo_white.svg
  docs/img/river_square.svg
  docs/overrides/home.html
  docs/recipes/on-hoeffding-trees_files/on-hoeffding-trees_21_0.png
  docs/recipes/on-hoeffding-trees_files/on-hoeffding-trees_23_0.png
  docs/recipes/on-hoeffding-trees_files/on-hoeffding-trees_25_0.png
  docs/recipes/on-hoeffding-trees_files/on-hoeffding-trees_27_0.png
  docs/recipes/pipelines.ipynb
  docs/stylesheets/extra.css
  mkdocs.yml
  river/compose/pipeline.py
Labels: codeball:approved

#962 Remove river_extra version constraint in setup.py
  setup.py
Labels: Improvement

#968 Optimized append sorted window
  river/utils/sorted_window.py
Labels: Improvement
