Repository online-ml/river, pull requests merged in 2022-09, with the labels that each got.

#1023 Refactor code and use Welford's algorithm to CluStream
  river/cluster/clustream.py
Labels: codeball:approved

#1028 Style nitpicks in TwitchChatStream
  river/stream/twitch_chat_stream.py
Labels: codeball:approved

#1025 Computationally intensive statistics in Rust
  .github/workflows/branch-docs.yml
  .github/workflows/branch-tests.yml
  .github/workflows/code-quality.yml
  .github/workflows/dev-docs.yml
  .github/workflows/pypi.yml
  .github/workflows/release-docs.yml
  .github/workflows/unit-tests.yml
  .gitignore
  CONTRIBUTING.md
  Cargo.toml
  MANIFEST.in
  Makefile
  pyproject.toml
  river/preprocessing/scale.py
  river/py.typed
  river/stats/_rust_stats.pyi
  river/stats/ewmean.py
  river/stats/ewvar.py
  river/stats/iqr.py
  river/stats/kurtosis.py
  river/stats/mad.py
  river/stats/ptp.py
  river/stats/quantile.py
  river/stats/skew.py
  river/stats/test_stats.py
  rust_src/lib.rs
  setup.py
Labels: Improvement, Performance, codeball:needs-careful-review

#1034 Add the Count-Min Sketch and introduce the new sketch module
  .github/workflows/branch-tests.yml
  .github/workflows/unit-tests.yml
  docs/releases/unreleased.md
  river/api.py
  river/misc/__init__.py
  river/misc/sdft.py
  river/misc/skyline.py
  river/sketch/__init__.py
  river/sketch/counter.py
  river/sketch/heavy_hitters.py
  river/sketch/histogram.py
  river/stats/__init__.py
  river/tree/splitter/histogram_splitter.py
Labels: codeball:needs-careful-review
